/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(root)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
